apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pipeline-demo
  template:
    metadata:
      labels:
        app: pipeline-demo
    spec:
      containers:
        - name: pipeline-demo
          image: trainingacrkmav.azurecr.io/pipeline-demo:3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3